/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ConexaoRouteImport } from './routes/conexao'
import { Route as CamerasRouteImport } from './routes/cameras'
import { Route as IndexRouteImport } from './routes/index'

const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexaoRoute = ConexaoRouteImport.update({
  id: '/conexao',
  path: '/conexao',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasRoute = CamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cameras': typeof CamerasRoute
  '/conexao': typeof ConexaoRoute
  '/eventos': typeof EventosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cameras': typeof CamerasRoute
  '/conexao': typeof ConexaoRoute
  '/eventos': typeof EventosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cameras': typeof CamerasRoute
  '/conexao': typeof ConexaoRoute
  '/eventos': typeof EventosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cameras' | '/conexao' | '/eventos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cameras' | '/conexao' | '/eventos'
  id: '__root__' | '/' | '/cameras' | '/conexao' | '/eventos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CamerasRoute: typeof CamerasRoute
  ConexaoRoute: typeof ConexaoRoute
  EventosRoute: typeof EventosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexao': {
      id: '/conexao'
      path: '/conexao'
      fullPath: '/conexao'
      preLoaderRoute: typeof ConexaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras': {
      id: '/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CamerasRoute: CamerasRoute,
  ConexaoRoute: ConexaoRoute,
  EventosRoute: EventosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
